services:
  publisher:
    container_name: go-publisher
    build: ./publisher/.
    ports:
      - '8080:8080'
    environment:
      - SERVER_URL=:8080
      - QUEUE_URL=amqp://guest:guest@go-queue:5672
      - QUEUE_NAME=go-main-queue
  subscriber:
    container_name: go-subscriber
    build: ./subscriber/.
    ports:
      - '8000:8000'
    environment:
      - SERVER_URL=:8000
      - QUEUE_URL=amqp://guest:guest@go-queue:5672
      - QUEUE_NAME=go-main-queue

  message-broker:
    container_name: go-queue
    image: rabbitmq:management
    ports:
      - 5672:5672   # for sender and consumer connections
      - 15672:15672 # for serve RabbitMQ GUI